export const VIEW_COMPANIES = 'VIEW_COMPANIES';
export const IS_LOAD_COMPANIES = 'IS_LOAD_COMPANIES';
export const VIEW_COMPANY = 'VIEW_COMPANY';
export const FILTER_COMPANY = 'FILTER_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPAMY';